# Generated by Django 6.0.2 on 2026-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='total_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
