# Generated by Django 6.0.2 on 2026-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_location_property_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
