# Generated by Django 6.0.2 on 2026-03-02 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_property_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clan',
            name='members',
            field=models.ManyToManyField(related_name='clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
