# Generated by Django 6.0.2 on 2026-03-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clan_leader_alter_clan_members_alter_clan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
