# Generated by Django 6.0.2 on 2026-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_wallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='property',
            new_name='property_obj',
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_dividend_per_share',
            field=models.FloatField(default=0.0),
        ),
    ]
