# Generated by Django 6.0.2 on 2026-03-20 20:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_investment_total_invested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
