# Generated by Django 6.0.2 on 2026-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_property_price_per_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminreply',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
