# Generated by Django 6.0.2 on 2026-03-21 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_usermessage_user_message_delete_adminreply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('ALLOCATE', 'Admin Allocation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet'),
        ),
    ]
