# Generated by Django 6.0.2 on 2026-03-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_timestamp_ledgerentry_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('hired_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wallet'),
        ),
    ]
