# Generated by Django 6.0.2 on 2026-03-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_staff_alter_ledgerentry_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='portfolio_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
